title:            Am Hahnenturm
tagline:          Erholung in der Pfalz

author:
  name:           Hillebrand
  
markdown:         kramdown
highlighter:      rouge
  
plugins:
  - jekyll-seo-tag
  
google_analytics: UA—XXXXXXXX-X
